## Site Meta ##
# The title of the website.
title: "Lens - 孟想"
# The description of the website
description: "A photo blog."
# Keywords/tags for you site.
keywords: "lens, photography, blog, photography-blog, photo-blog, 图片, 孟想"
# Your copyright message.
copyright: "Copyright &copy; 2018 - 孟想."

## Site Configurations ##
# 1st heading of the site.
header: "Lens"
# 2nd heading/sub heading of the website.
subheader: "孟想"
# A description/bio of the website.
bio: "A photo blog."
social:
  # Your Twitter username.
  twitter_username: "mlkey"
  # Your Facebook username.
  facebook_username: "mlkey"
  # Your Instagram username.
  instagram_username: "mlkey"
  # GitHub username.
  github_username: "mlkey"
  # Your email address.
  email: "mlkey@126.com"

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
gallery_dir: "gallery"
# Any valid value of "background-position" CSS attribute.
image_position: "left center"

## Jekyll Configuration ##
defaults:
 - scope:
    # Should be same as the `gallery_dir` key above.
    path: "gallery"
   values:
    image: true
